import {Skill} from './Skill'

export const SKILLS: Skill[] = [{ id:1, skill:'Agile Development' },
{ id: 2, skill: 'Test Driven Development' }, 
{ id: 3, skill: 'Core Java' }, 
{ id: 4, skill: 'Spring' }, 
{ id: 5, skill: 'Spring Boot' }, 
{ id: 6, skill: 'MySQL' },
{ id: 7, skill: 'Hibernate' },
{ id: 8, skill: 'Postman' }, 
{ id: 9, skill: 'Microservices' },
{ id: 10, skill: 'Rest APIs' },
{ id: 11, skill: 'HTML' },
{ id: 12, skill: 'CSS' },
{ id: 13, skill: 'TypeScript' },
{ id: 14, skill: 'Angular' },
{ id: 15, skill: 'AWS' },
{ id: 16, skill: 'Git' },
{ id: 17, skill: 'GitHub' },
{ id: 18, skill: 'Node.js' },
{ id: 19, skill: 'React' },
{ id: 20, skill: 'Google Cloud Platform (Queries & Deployment)' },
{ id: 21, skill: 'Microsoft Office & Teams' },
{ id: 22, skill: 'Google Drive' },
{ id: 23, skill: 'MATLAB' },
{ id: 24, skill: 'Python' },
{ id: 25, skill: 'Ubuntu' },
{ id: 26, skill: 'Linux' },
{ id: 27, skill: 'Testing 1' },
{ id: 28, skill: 'Testing 2' }];